version: "3"

services:
  backend:
    build: ./backend
    env_file:
      - .env
      - backend/.env
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: >
      sh -c "
        npx prisma generate &&
        npm run start
      "

  frontend:
    build: ./frontend
    env_file:
      - frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # command: npm run dev
